---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: berto-virt-gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    cudn: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
