apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gitops-demo-f44-vm-02
  namespace: berto-virt-gitops-demo
  labels:
    app: gitops-demo-f44-vm-02
    kubevirt.io/dynamic-credentials-support: "true"
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.32.2
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: gitops-demo-f44-vm-02-dv
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: gitops-demo-f44-vm-02
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
        vm-group: gitops-demo-f44-vmgroup
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              model: virtio
              bridge: {}
              state: up
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
        resources: {}
      networks:
        - name: default
          multus:
            networkName: vlan-2103-cudn
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: gitops-demo-f44-vm-02-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: gitops-demo-f44-vm-02-cloudinit
            networkDataSecretRef:
              name: gitops-demo-f44-vm-02-cloudinit
